name: Release & Publish

on:
  workflow_run:
    workflows:
      - CI
    types:
      - completed

concurrency:
  group: release-publish-${{ github.event.workflow_run.head_branch }}
  cancel-in-progress: false

jobs:
  build:
    name: Build & Package
    if: >-
      ${{ github.event.workflow_run.conclusion == 'success' &&
          github.event.workflow_run.head_branch == 'main' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      tarball: ${{ steps.pack.outputs.tarball }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Set up pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: false

      - name: pnpm store path
        id: pnpm-store
        run: echo "store-path=$(pnpm store path --silent)" >> "$GITHUB_OUTPUT"

      - name: Cache pnpm store
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-store.outputs.store-path }}
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Type check
        run: pnpm typecheck

      - name: Build package
        run: pnpm build

      - name: Pack npm artifact
        id: pack
        run: |
          rm -rf package-artifacts
          mkdir -p package-artifacts
          pnpm pack --pack-destination package-artifacts --silent
          TAR_PATH=$(find package-artifacts -maxdepth 1 -name '*.tgz' -print -quit)
          TAR_NAME=$(basename "$TAR_PATH")
          {
            echo "tarball=$TAR_NAME"
            echo "tarball_path=$TAR_PATH"
          } >> "$GITHUB_OUTPUT"

      - name: Upload packaged artifact
        uses: actions/upload-artifact@v4
        with:
          name: package-tarball
          path: package-artifacts/${{ steps.pack.outputs.tarball }}
          if-no-files-found: error

  release:
    name: Create GitHub Release
    needs: build
    if: >-
      ${{ needs.build.result == 'success' &&
          github.event.workflow_run.conclusion == 'success' &&
          github.event.workflow_run.head_branch == 'main' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      created: ${{ steps.decision.outputs.created }}
      version: ${{ steps.metadata.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Determine package metadata
        id: metadata
        run: |
          VERSION=$(node -p "require('./package.json').version")
          NAME=$(node -p "require('./package.json').name")
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
          echo "tag=v$VERSION" >> "$GITHUB_OUTPUT"
          echo "name=$NAME" >> "$GITHUB_OUTPUT"

      - name: Check for existing release
        id: release_check
        uses: actions/github-script@v7
        env:
          TAG_NAME: v${{ steps.metadata.outputs.version }}
        with:
          script: |
            const tag = process.env.TAG_NAME;
            try {
              await github.rest.repos.getReleaseByTag({
                owner: context.repo.owner,
                repo: context.repo.repo,
                tag,
              });
              core.setOutput('exists', 'true');
            } catch (error) {
              if (error.status === 404) {
                core.setOutput('exists', 'false');
              } else {
                throw error;
              }
            }

      - name: Decide whether to release
        id: decision
        run: |
          if [ "${{ steps.release_check.outputs.exists }}" = "true" ]; then
            echo "created=false" >> "$GITHUB_OUTPUT"
          else
            echo "created=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Download package artifact
        if: steps.decision.outputs.created == 'true'
        uses: actions/download-artifact@v4
        with:
          name: package-tarball
          path: release-artifacts

      - name: Create GitHub release
        if: steps.decision.outputs.created == 'true'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.metadata.outputs.version }}
          name: ${{ steps.metadata.outputs.name }} ${{ steps.metadata.outputs.version }}
          body: |
            Automated release for ${{ steps.metadata.outputs.name }} v${{ steps.metadata.outputs.version }}.
          files: release-artifacts/${{ needs.build.outputs.tarball }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-npm:
    name: Publish to npm
    needs:
      - build
      - release
    if: >-
      ${{ needs.release.result == 'success' &&
          needs.release.outputs.created == 'true' &&
          github.event.workflow_run.conclusion == 'success' &&
          github.event.workflow_run.head_branch == 'main' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Download package artifact
        uses: actions/download-artifact@v4
        with:
          name: package-tarball
          path: package

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - name: Publish package
        run: npm publish package/${{ needs.build.outputs.tarball }} --access public --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
